AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  asciiart-lambda-1

  Sample SAM Template for asciiart-lambda-1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    BinaryMediaTypes:
      - "*~1*"
Resources:
  AsciiArtFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: AsciiArtFunction
      Handler: asciiart.App::handleRequest
      Runtime: java17
      Architectures:
      - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          TMPDIR: /Users/rolandtreiber/projects/temp
      Events:
        AsciiArt:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /convert-and-save
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AsciiArtApi:
    Description: API Gateway endpoint URL for Prod stage for AsciiArt function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/asciiart/"
  AsciiArtFunction:
    Description: Ascii Art Lambda Function ARN
    Value: !GetAtt AsciiArtFunction.Arn
  AsciiArtFunctionIamRole:
    Description: Implicit IAM Role created for Ascii Art function
    Value: !GetAtt AsciiArtFunctionRole.Arn
